# directories
data_path: '...'
save_dir: '...'
save_dir_metrics: '...'


# general settings
verbose: False
show_training: True
seed: 42
device: cuda


# data settings
img_width: 128
img_height: 128
n_channels: 3
validation_ratio: 0.2


# hyperparameters
num_epochs: 100
batch_size: 32
lr: 0.001


# training settings
early_stopping: True
lr_scheduler: True
transform: False




